name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Documentation (Doxygen + Sphinx)
        env:
          GA_ANALYTICS_ID: ${{ secrets.GA_ANALYTICS_ID }}
          GITHUB_URL: ${{ vars.DOCS_GITHUB_URL }}
          ESP_REGISTRY_URL: ${{ vars.DOCS_ESP_REGISTRY_URL }}
        run: |
          cd docs
          doxygen Doxyfile
          sphinx-build -b html . _build/html

      - name: Display Doxygen Warnings
        if: always()
        run: |
          WARN_LOG="docs/_build/doxygen-warnings.log"
          if [ -s "$WARN_LOG" ]; then
            echo "::warning::Doxygen found documentation issues! Emitting log:"
            cat "$WARN_LOG"
          else
            echo "Great job! No Doxygen warnings found."
          fi

      - name: Upload HTML Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4