name: Release and publish on ESP Registry

on:
  push:
    tags:
      - 'test-v*'
      - 'pt2258_ctrl-v*'

jobs:
  esp-registry:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse Component Name from Tag
        id: target
        run: |
          TAG_NAME=${{ github.ref_name }}
          COMP_NAME=$(echo "$TAG_NAME" | cut -d'-' -f1)
          
          echo "name=${COMP_NAME}" >> $GITHUB_OUTPUT
          echo "path=./${COMP_NAME}" >> $GITHUB_OUTPUT

      - name: Upload to ESP Component Registry
        uses: espressif/upload-components-ci-action@v2
        with:
          namespace: "romr"
          components: "${{ steps.target.outputs.name }}:${{ steps.target.outputs.path }}"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          dry_run: true